### ISSUE TITLE
pbl under linux 

### ISSUE THREAD

**Issue by cokelaer** [sequana/sequanix#4]
Traceback (most recent call last):
      File "/home/cokelaer/miniconda3/envs/sequana/bin/sequanix", line 5, in     <module>
      from sequanix import main
     File "/home/cokelaer/miniconda3/envs/sequana/lib/python3.7/site-packages/sequanix/__init__.py", line 1, in <module>
       from .sequanix import SequanixGUI, main
     File "/home/cokelaer/miniconda3/envs/sequana/lib/python3.7/site-packages/sequanix/sequanix.py", line 39, in <module>
       from .widgets import (
     File "/home/cokelaer/miniconda3/envs/sequana/lib/python3.7/site-packages/sequanix/widgets/__init__.py", line 2, in <module>
       from .browser import Browser
     File "/home/cokelaer/miniconda3/envs/sequana/lib/python3.7/site-packages/sequanix/widgets/browser.py", line 3, in <module>
       from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEnginePage, QWebEngineSettings
    ImportError: /lib64/libgssapi_krb5.so.2: undefined symbol: k5_internalize_principal, version krb5_3_MIT

**Comment by cokelaer** [comment]
looks like it works now. Just a missing tqdm import that can be easily fix with

   pip install tqdm

and will be fix with future release of sequana_pipetools
